# @format

menubar:
    columns: 1 # 一行多少个
    items: # 可按照自己需求增加，符合以下格式即可
        - id: about
        theme: ""
        title: About
        icon: ""
        url: /about/

article:
    type: tech # tech/story
    auto_cover: true
    auto_excerpt: 500
