# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Programming Diary 
avatar: https://github.com/Huaiyuan-Jing/BlogBase/blob/main/Hatta.png?raw=true
favicon: https://github.com/Huaiyuan-Jing/BlogBase/blob/main/Hatta.png?raw=true
subtitle: ''
description: ''
keywords:
author: HuaiYuan Jing
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://huaiyuan-jing.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/Huaiyuan-Jing/Huaiyuan-Jing.github.io
  branch: master

index:
  banner_img: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/280eb5fb-52ae-4a64-be81-a582754c61ae/d82mts1-d4b8cd8b-b693-419f-92df-386bbfb7a862.png/v1/fill/w_1280,h_854,q_80,strp/solaire_of_astora_by_admhire_d82mts1-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODU0IiwicGF0aCI6IlwvZlwvMjgwZWI1ZmItNTJhZS00YTY0LWJlODEtYTU4Mjc1NGM2MWFlXC9kODJtdHMxLWQ0YjhjZDhiLWI2OTMtNDE5Zi05MmRmLTM4NmJiZmI3YTg2Mi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.yuTdOAvUaDaIMDArLdCLyZf_KNwOKDNawveUThApmtE
  banner_img_height: 100
  banner_mask_alpha: 0.2
  slogan:
    enable: true
    text: "All those moments will be lost in time, like tears in rain." 
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

post:
  banner_img: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/280eb5fb-52ae-4a64-be81-a582754c61ae/d82mts1-d4b8cd8b-b693-419f-92df-386bbfb7a862.png/v1/fill/w_1280,h_854,q_80,strp/solaire_of_astora_by_admhire_d82mts1-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODU0IiwicGF0aCI6IlwvZlwvMjgwZWI1ZmItNTJhZS00YTY0LWJlODEtYTU4Mjc1NGM2MWFlXC9kODJtdHMxLWQ0YjhjZDhiLWI2OTMtNDE5Zi05MmRmLTM4NmJiZmI3YTg2Mi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.yuTdOAvUaDaIMDArLdCLyZf_KNwOKDNawveUThApmtE
  banner_img_height: 100
  banner_mask_alpha: 0.2
  math:
    enable: true
    specific: true
    engine: mathjax

about:
  banner_img: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/280eb5fb-52ae-4a64-be81-a582754c61ae/d82mts1-d4b8cd8b-b693-419f-92df-386bbfb7a862.png/v1/fill/w_1280,h_854,q_80,strp/solaire_of_astora_by_admhire_d82mts1-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODU0IiwicGF0aCI6IlwvZlwvMjgwZWI1ZmItNTJhZS00YTY0LWJlODEtYTU4Mjc1NGM2MWFlXC9kODJtdHMxLWQ0YjhjZDhiLWI2OTMtNDE5Zi05MmRmLTM4NmJiZmI3YTg2Mi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.yuTdOAvUaDaIMDArLdCLyZf_KNwOKDNawveUThApmtE
  banner_img_height: 100
  banner_mask_alpha: 0.2
  icons: 
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/Huaiyuan-Jing', tip: 'GitHub' } 
    - { class: 'iconfont icon-linkedin-fill', link: 'https://www.linkedin.com/in/huaiyuan-jing-823b93240/', tip: 'GitHub' } 
  avatar: https://github.com/Huaiyuan-Jing/BlogBase/blob/main/RetHat.png?raw=true
  name: "Lucien Jing"
  intro: "Long May The Sunshine"

links:
  banner_img: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/280eb5fb-52ae-4a64-be81-a582754c61ae/d82mts1-d4b8cd8b-b693-419f-92df-386bbfb7a862.png/v1/fill/w_1280,h_854,q_80,strp/solaire_of_astora_by_admhire_d82mts1-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODU0IiwicGF0aCI6IlwvZlwvMjgwZWI1ZmItNTJhZS00YTY0LWJlODEtYTU4Mjc1NGM2MWFlXC9kODJtdHMxLWQ0YjhjZDhiLWI2OTMtNDE5Zi05MmRmLTM4NmJiZmI3YTg2Mi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.yuTdOAvUaDaIMDArLdCLyZf_KNwOKDNawveUThApmtE
  banner_img_height: 100
  banner_mask_alpha: 0.2
  items:
    - {
      title: 'Compiled Thought',
      intro: 'Author: NoNullIsInHeaven',
      link: 'https://compiled-thoughts.fyi/',
      avatar: 'https://compiled-thoughts.fyi/wp-content/uploads/2025/01/1736927147-Yunyun-with-KR-square.png'
    }

dark_mode:
  enable: true
  default: auto

lazyload:
  enable: true
  loading_img: https://github.com/Huaiyuan-Jing/BlogBase/blob/main/Sisyphus.jpg?raw=true
  onlypost: false
  offset_factor: 2

navbar:
  blog_title: Programming Diary
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill', name: 'Home' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill', name: 'Tag' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: 'About' }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
